// Rover Cruse Control
// Throttle PIDLoop
PARAMETER thrSP IS 5.
SET thrMin TO -1.
SET thrMax TO 1.
SET thrKp TO 0.75.
SET thrKi TO 0.02.
SET thrKd TO 0.15.
SET thrPID TO PIDLoop(thrKp, thrKi, thrKd, thrMin, thrMax).
SET thrPID:SETPOINT TO thrSP.

SET thr TO 1.
LOCK WHEELTHROTTLE TO thr.

UNTIL BRAKES { SET thr TO MAX(MIN(1, thrPID:UPDATE(TIME:SECONDS, SHIP:GROUNDSPEED)), 0). }

SET THR TO 0.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
UNLOCK WHEELTHROTTLE.
